name: PR

on: pull_request

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 12
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
